### ISSUE TITLE
needs update for python3.11: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by tillea** [RazerM/ratelimiter#18]
Hi,
as [reported in the Debian bug tracking system](https://bugs.debian.org/1025119) ratelimiter does not work with python3.11:

    Python 3.11.1 (main, Dec  7 2022, 08:49:13) [GCC 12.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ratelimiter
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/andreas/debian-maintain/salsa/python-team/packages/python-ratelimiter/ratelimiter.py", line 36, in <module>
        class RateLimiter(object):
      File "/home/andreas/debian-maintain/salsa/python-team/packages/python-ratelimiter/ratelimiter.py", line 127, in RateLimiter    
        __aexit__ = asyncio.coroutine(__exit__)
                    ^^^^^^^^^^^^^^^^^
    AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

Kind regards, Andreas.

**Comment by venkatamutyala** [comment]
can we get a release?
